export const illnessOptions = [
  "Fever",
  "Cough",
  "Flu",
  "Cold",
  "Diabetes",
  "Hypertension",
  "Asthma",
  "Migraine",
  "Allergy",
  "Back pain",
  "Joint pain",
  "Thyroid",
  "Acne",
  "Infection",
  "Sinusitis",
  "Arthritis",
  "Depression",
  "Anxiety",
  "Insomnia",
  "Pneumonia",
  "Bronchitis",
  "Ulcers",
  "Gastritis",
  "Ear pain",
  "Eye strain",
  "Headache",
  "Skin rash",
  "Dizziness",
  "Vomiting",
  "Others",
];

export const firstAidOptions = [
  "Burn",
  "Cut",
  "Fracture",
  "Sprain",
  "Nosebleed",
  "Shock",
  "Choking",
  "CPR",
  "Bite",
  "Bleeding",
  "Head injury",
  "Allergic reaction",
  "Heat stroke",
  "Hypothermia",
  "Poisoning",
  "Fainting",
  "Seizure",
  "Dislocation",
  "Electric shock",
  "Others",
];

export const fitnessOptions = [
  "Weight loss",
  "Weight gain",
  "Muscle building",
  "Cardio",
  "Flexibility",
  "Yoga",
  "Strength training",
  "Running",
  "Cycling",
  "Swimming",
  "Crossfit",
  "HIIT",
  "Pilates",
  "Bodybuilding",
  "Stretching",
  "Endurance",
  "Zumba",
  "Athletic training",
  "Posture correction",
  "Others",
];

export const dietaryOptions = [
  "Vegan",
  "Vegetarian",
  "Keto",
  "Low-carb",
  "High-protein",
  "Low-fat",
  "Diabetic-friendly",
  "Heart-healthy",
  "Low-sodium",
  "Gluten-free",
  "Paleo",
  "Mediterranean",
  "Intermittent fasting",
  "Weight loss",
  "Weight gain",
  "Balanced",
  "High-fiber",
  "Raw food",
  "Detox",
  "Others",
];
